lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/numberbox-card/numberbox-card.js
      type: module

input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_text: !include includes/input_text.yaml
input_select: !include includes/input_select.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml

# Include folders
automation: !include_dir_merge_list includes/automation
